export const Questions = [
  {
    prompt: "What does HTML stand for?",
    optionA: "Hyper Trainer Marking Language",
    optionB: "Hyper Text Markup Language",
    optionC: "Hyper Text Marketing Language",
    optionD: "Hyper Text Markup Leveler",
    answer: "optionB",
  },
  {
    prompt: "What is the correct syntax for referring to an external script called 'script.js'?",
    optionA: "<script href='script.js'>",
    optionB: "<script name='script.js'>",
    optionC: "<script src='script.js'>",
    optionD: "<script link='script.js'>",
    answer: "optionC",
  },
  {
    prompt: "Which of the following is a JavaScript framework?",
    optionA: "Django",
    optionB: "React",
    optionC: "Flask",
    optionD: "Laravel",
    answer: "optionB",
  },
  {
    prompt: "Which company developed the React library?",
    optionA: "Google",
    optionB: "Microsoft",
    optionC: "Facebook",
    optionD: "Amazon",
    answer: "optionC",
  },
  {
    prompt: "What does CSS stand for?",
    optionA: "Colorful Style Sheets",
    optionB: "Cascading Style Sheets",
    optionC: "Computer Style Sheets",
    optionD: "Creative Style Sheets",
    answer: "optionB",
  },
  {
    prompt: "Which programming language is primarily used for Android app development?",
    optionA: "Swift",
    optionB: "Kotlin",
    optionC: "Python",
    optionD: "C++",
    answer: "optionB",
  },
  {
    prompt: "In Python, which of the following is used to define a function?",
    optionA: "def",
    optionB: "func",
    optionC: "function",
    optionD: "lambda",
    answer: "optionA",
  },
  {
    prompt: "What does SQL stand for?",
    optionA: "Structured Query Language",
    optionB: "System Query Language",
    optionC: "Simplified Query Language",
    optionD: "Standard Query Language",
    answer: "optionA",
  },
  {
    prompt: "Which of the following is used to style a React Native component?",
    optionA: "class",
    optionB: "style",
    optionC: "css",
    optionD: "stylesheet",
    answer: "optionD",
  },
  {
    prompt: "Which of the following is not a NoSQL database?",
    optionA: "MongoDB",
    optionB: "Firebase",
    optionC: "PostgreSQL",
    optionD: "CouchDB",
    answer: "optionC",
  },
  {
    prompt: "Which JavaScript method is used to parse a string to JSON?",
    optionA: "JSON.parse()",
    optionB: "JSON.stringify()",
    optionC: "JSON.convert()",
    optionD: "JSON.toString()",
    answer: "optionA",
  },
  {
    prompt: "Which of the following is not a Git command?",
    optionA: "git clone",
    optionB: "git fork",
    optionC: "git commit",
    optionD: "git pull",
    answer: "optionB",
  },
  {
    prompt: "Which type of database is Firebase?",
    optionA: "Document-oriented database",
    optionB: "Relational database",
    optionC: "Graph database",
    optionD: "Key-value store",
    answer: "optionA",
  },
  {
    prompt: "Which CSS property is used to change the text color of an element?",
    optionA: "font-color",
    optionB: "text-color",
    optionC: "color",
    optionD: "font-style",
    answer: "optionC",
  },
  {
    prompt: "Which method is used to remove the last element from an array in JavaScript?",
    optionA: "shift()",
    optionB: "pop()",
    optionC: "splice()",
    optionD: "split()",
    answer: "optionB",
  },
  {
    prompt: "Which of the following is a strongly typed language?",
    optionA: "JavaScript",
    optionB: "Python",
    optionC: "C++",
    optionD: "PHP",
    answer: "optionC",
  },
  {
    prompt: "Which version control system is most commonly used?",
    optionA: "Git",
    optionB: "SVN",
    optionC: "Mercurial",
    optionD: "Bazaar",
    answer: "optionA",
  },
  {
    prompt: "Which HTML tag is used to define an internal stylesheet?",
    optionA: "<script>",
    optionB: "<css>",
    optionC: "<style>",
    optionD: "<link>",
    answer: "optionC",
  },
  {
    prompt: "Which HTTP method is used to update an existing resource?",
    optionA: "GET",
    optionB: "POST",
    optionC: "PUT",
    optionD: "DELETE",
    answer: "optionC",
  },
  {
    prompt: "Which of the following is a cloud platform for hosting websites and web applications?",
    optionA: "Google Cloud",
    optionB: "Docker",
    optionC: "Jenkins",
    optionD: "Kubernetes",
    answer: "optionA",
  }
];
